export const colors = {
  //primary-------------------------------------------
  primary: '#292D32',
  primaryLight: '#3A3A3A',
  primaryLighter: '#9A9FA5',
  primaryLightest: '#0085ff',
  primaryDark: '#000744',
  primaryDarker: '#000530',
  middlePrimary: '#53575B',
  primaryTransparent: 'rgba(0, 0, 0, 0.51)',
  subscription: '#8D76FF',
  created: '#4CA1FF',
  saved: '#39DA87',
  spent: '#FFA43B',

  //commaon-------------------------------------------
  white: '#ffffff',
  offWhite: '#f8f8ff',
  secondary: '#FAFAFA',
  transparent: '#00000099',
  black: '#000000',
  metallicBlack: '#333333',
  direWolf: '#282828',
  lightestGray: '#DFDFDF',
  gray: '#696969',
  lightGray: '#979CA5',
  darkGray: '#464646',
  green: '#006203',
  redDark: '#880808',
  red: '#DB2121',
  transparentRed: 'rgba(219, 33, 33, 0.05)',
  pink: '#ED1878',
  background: '#F7F7F7',
  flagButton: '#E8E8E8',
  lightBorder: '#C9C9C9',
  darkBoder: '#767676',
  success: '#27b743',
  info: '#4182ff',
  warning: '#FFC107',
  error: '#f34545',
  blue: '#1665FF',
  neavyBlue: '#1C3972',
  lighterBlue: '#7FABFF',

  pf1: '#0057FF66',
  pf2: '#9000FF66',
  pf3: '#FF950066',
  pf4: '#00D44766',
  pf5: '#D399FF',
  pf6: '#FF006A66',
  pf7: '#0083D466',
  pf8: '#fc8181',
};
//light--------------------------------------------
export const lightThemeColors = {
  primary: colors.primary,
  primaryDark: colors.primaryDark,
  primaryDarker: colors.primaryDarker,
  primaryLight: colors.primaryLight,
  primaryLighter: colors.primaryLighter,
  primaryLightest: colors.primaryLightest,
  whitePrimary: colors.white,
  primaryWhite: colors.primary,
  background: colors.background,
  darkGrayWhite: colors.darkGray,
  whiteBlack: colors.white,
  blackWhite: colors.primary,
  primaryMiddlePrimary: colors.primary,
  primaryLightMiddlePrimary: colors.primaryLight,
  black: colors.primary,
};

//dark---------------------------------------------
export const darkThemeColors = {
  primary: colors.primaryDark,
  primaryDark: colors.primaryDark,
  primaryDarker: colors.primaryDarker,
  primaryLight: colors.primaryLight,
  primaryLighter: colors.primaryLighter,
  primaryLightest: colors.primaryLightest,
  whitePrimary: colors.primary,
  primaryWhite: colors.white,
  background: colors.primaryLight,
  darkGrayWhite: colors.white,
  whiteBlack: colors.primary,
  blackWhite: colors.white,
  primaryMiddlePrimary: colors.middlePrimary,
  primaryLightMiddlePrimary: colors.middlePrimary,
  black: colors.primary,
};
